---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaosfs-tiflash
  namespace: chaos-testing
  labels:
    app.kubernetes.io/component: webhook
data:
  chaosfs-tiflash.yaml: |
    name: chaosfs-tiflash
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "tiflash"
    initContainers:
    - name: inject-scripts
      image: pingcap/chaos-scripts:latest
      imagePullpolicy: Always
      command: ["sh", "-c", "/scripts/init.sh -d /data0/db -f /data0/fuse-data"]
    containers:
    - name: chaosfs
      image: pingcap/chaos-fs:latest
      imagePullpolicy: Always
      ports:
      - containerPort: 65534
      securityContext:
        privileged: true
      command:
        - /usr/local/bin/chaosfs
        - -addr=:65534
        - -pidfile=/tmp/fuse/pid
        - -original=/data0/fuse-data
        - -mountpoint=/data0/db
      volumeMounts:
        - name: data
          mountPath: /data0
          mountPropagation: Bidirectional
    volumeMounts:
    - name: data
      mountPath: /data0
      mountPropagation: HostToContainer
    - name: scripts
      mountPath: /tmp/scripts
    - name: fuse
      mountPath: /tmp/fuse
    volumes:
    - name: scripts
      emptyDir: {}
    - name: fuse
      emptyDir: {}
    postStart:
      tiflash:
        command:
          - /tmp/scripts/wait-fuse.sh