name: "Pre-Check"
on: push

jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v2

      - name: "tidy"
        run: make tidy

      - name: "format"
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get golang.org/x/tools/cmd/goimports
          make fmt

      - name: "lint"
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/mgechev/revive@v1.0.2
          make lint

